export const data=[
    {
        image:"/images/wedding.jpeg",
        name:"uttejvarma",
        price:10000,
        location:"bangalore"
    },
    {
        image:"/images/college.jpeg",
        name:"varma",
        price:10000,
        location:"bangalore"
    },
    {
        image:"/images/proposal.jpeg",
        name:"uttej",
        price:10000,
        location:"bangalore"
    },
    {
        image:"/images/concert.jpeg",
        name:"xyz",
        price:10000,
        location:"bangalore"
    },
    {
        image:"/images/birthday.jpeg",
        name:"uttejvarma",
        price:10000,
        location:"bangalore"
    },
    {
        image:"/images/wedding.jpeg",
        name:"uttejvarma",
        price:10000,
        location:"bangalore"
    },
    {
        image:"/images/college.jpeg",
        name:"uttejvarma",
        price:10000,
        location:"bangalore"
    },
    {
        image:"/images/proposal.jpeg",
        name:"uttejvarma",
        price:10000,
        location:"bangalore"
    },
    {
        image:"/images/concert.jpeg",
        name:"uttejvarma",
        price:10000,
        location:"bangalore"
    },
    {
        image:"/images/birthday.jpeg",
        name:"uttejvarma",
        price:10000,
        location:"bangalore"
    },
    {
        image:"/images/wedding.jpeg",
        name:"uttejvarma",
        price:10000,
        location:"bangalore"
    },
    {
        image:"/images/college.jpeg",
        name:"uttejvarma",
        price:10000,
        location:"bangalore"
    },
    {
        image:"/images/proposal.jpeg",
        name:"uttejvarma",
        price:10000,
        location:"bangalore"
    },
    {
        image:"/images/concert.jpeg",
        name:"uttejvarma",
        price:10000,
        location:"bangalore"
    },
    {
        image:"/images/birthday.jpeg",
        name:"uttejvarma",
        price:10000,
        location:"bangalore"
    }
];
export const smallData=[
    {
        image:"/images/wedding.jpeg",
        name:"uttejvarma",
        price:10000,
        location:"bangalore"
    },
    {
        image:"/images/college.jpeg",
        name:"uttejvarma",
        price:10000,
        location:"bangalore"
    },
    {
        image:"/images/proposal.jpeg",
        name:"uttejvarma",
        price:10000,
        location:"bangalore"
    },
    {
        image:"/images/concert.jpeg",
        name:"uttejvarma",
        price:10000,
        location:"bangalore"
    },
    {
        image:"/images/birthday.jpeg",
        name:"uttejvarma",
        price:10000,
        location:"bangalore"
    },
    {
        image:"/images/wedding.jpeg",
        name:"uttejvarma",
        price:10000,
        location:"bangalore"
    }
]